services:
  backend:
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      mongo:
        condition: service_healthy