services:
  # TS frontend
  frontend:
    build: apps/frontend
    container_name: ts-frontend
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - cache:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    read_only: false
    profiles:
      - frontend
      - prod

  # Go backend
  backend:
    build: apps/backend
    container_name: go-backend
    networks:
      - app_network
      - rpc_network
      - db_network
      - kafka_network
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - POSTGRES_DSN=postgres://admin:${POSTGRES_PASSWORD}@db:5432/secure-voting?sslmode=disable
      - TOKEN_TTL=720h
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_ADDR=cache:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - IDEMPOTENCY_TTL=24h
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - backend
      - prod

  # SQL Postgres db
  db:
    image: postgres:18.1
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=secure-voting
      - POSTGRES_USER=admin
    networks:
      - db_network
    volumes:
      - db-data:/var/lib/postgresql
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d secure-voting"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - db
      - prod

  # Postgres WebUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-webui
    ports:
      - "127.0.0.1:15433:80"
    networks:
      - db_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db
    read_only: false
    profiles:
      - db
      - debug

  # Redis cache
  cache:
    image: redis:8.4
    container_name: redis-cache
    networks:
      - app_network
      - redis_network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      sh -c 'redis-server --save 20 1 --loglevel warning --requirepass "$$REDIS_PASSWORD"'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis WebUI
  redis-webui:
    image: redis/redisinsight:2.70
    container_name: redis-webui
    ports:
      - "127.0.0.1:5540:5540"
    networks:
      - redis_network
    restart: unless-stopped
    volumes:
      - redisinsight-data:/data
    depends_on:
      - cache
    read_only: true
    profiles:
      - db
      - debug

  # NoSQL MongoDB
  mongo:
    image: mongo:8.0
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - db_network
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")'"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - db
      - prod

  mongodb-webui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongodb-webui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:8082:8081"
    networks:
      - db_network
    restart: unless-stopped
    depends_on:
      - mongo
    read_only: false
    profiles:
      - db
      - debug

  # Compute core
  compute:
    build: apps/compute
    container_name: rust-compute
    networks:
      - rpc_network
    restart: unless-stopped
    read_only: true
    profiles:
      - compute
      - prod


  # Kafka (KRaft, local-dev friendly)
  kafka:
    image: confluentinc/confluent-local:7.6.9-1-ubi8
    container_name: kafka
    networks:
      - kafka_network
    ports:
      - "9092:9092"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
    profiles:
      - kafka
      - prod


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "127.0.0.1:8089:8080"
    networks:
      - kafka_network
    restart: unless-stopped
    profiles:
      - debug


networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge
    internal: true
  rpc_network:
    driver: bridge
    internal: true
  redis_network:
    driver: bridge
  kafka_network:
    driver: bridge
    internal: true


volumes:
  db-data:
    driver: local
  cache:
    driver: local
  mongo-data:
    driver: local
  kafka-data:
    driver: local
  pgadmin-data:
    driver: local
  redisinsight-data:
    driver: local
