services:
  backend:
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      mongo:
        condition: service_healthy

  cache:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      sh -c 'redis-server --save 20 1 --loglevel warning --requirepass "$$REDIS_PASSWORD"'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
