// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: compute_v1.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compute_Run_FullMethodName            = "/securevoting.compute.v1.Compute/Run"
	Compute_ListTallyRules_FullMethodName = "/securevoting.compute.v1.Compute/ListTallyRules"
)

// ComputeClient is the client API for Compute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeClient interface {
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunChunk, RunResult], error)
	ListTallyRules(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTallyRulesResponse, error)
}

type computeClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeClient(cc grpc.ClientConnInterface) ComputeClient {
	return &computeClient{cc}
}

func (c *computeClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunChunk, RunResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compute_ServiceDesc.Streams[0], Compute_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunChunk, RunResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_RunClient = grpc.ClientStreamingClient[RunChunk, RunResult]

func (c *computeClient) ListTallyRules(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListTallyRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTallyRulesResponse)
	err := c.cc.Invoke(ctx, Compute_ListTallyRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServer is the server API for Compute service.
// All implementations must embed UnimplementedComputeServer
// for forward compatibility.
type ComputeServer interface {
	Run(grpc.ClientStreamingServer[RunChunk, RunResult]) error
	ListTallyRules(context.Context, *empty.Empty) (*ListTallyRulesResponse, error)
	mustEmbedUnimplementedComputeServer()
}

// UnimplementedComputeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeServer struct{}

func (UnimplementedComputeServer) Run(grpc.ClientStreamingServer[RunChunk, RunResult]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedComputeServer) ListTallyRules(context.Context, *empty.Empty) (*ListTallyRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTallyRules not implemented")
}
func (UnimplementedComputeServer) mustEmbedUnimplementedComputeServer() {}
func (UnimplementedComputeServer) testEmbeddedByValue()                 {}

// UnsafeComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServer will
// result in compilation errors.
type UnsafeComputeServer interface {
	mustEmbedUnimplementedComputeServer()
}

func RegisterComputeServer(s grpc.ServiceRegistrar, srv ComputeServer) {
	// If the following call panics, it indicates UnimplementedComputeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compute_ServiceDesc, srv)
}

func _Compute_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServer).Run(&grpc.GenericServerStream[RunChunk, RunResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_RunServer = grpc.ClientStreamingServer[RunChunk, RunResult]

func _Compute_ListTallyRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServer).ListTallyRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compute_ListTallyRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServer).ListTallyRules(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Compute_ServiceDesc is the grpc.ServiceDesc for Compute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "securevoting.compute.v1.Compute",
	HandlerType: (*ComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTallyRules",
			Handler:    _Compute_ListTallyRules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Compute_Run_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "compute_v1.proto",
}
