// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: compute_v1.proto

package pb

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_compute_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RunHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RunId              string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ElectionId         string                 `protobuf:"bytes,3,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	ExperimentId       string                 `protobuf:"bytes,4,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	DatasetId          string                 `protobuf:"bytes,5,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TallyRule          string                 `protobuf:"bytes,6,opt,name=tally_rule,json=tallyRule,proto3" json:"tally_rule,omitempty"`
	BallotFormat       string                 `protobuf:"bytes,7,opt,name=ballot_format,json=ballotFormat,proto3" json:"ballot_format,omitempty"`
	CommitteeSize      *wrappers.Int32Value   `protobuf:"bytes,8,opt,name=committee_size,json=committeeSize,proto3" json:"committee_size,omitempty"`
	QuotaType          *wrappers.StringValue  `protobuf:"bytes,9,opt,name=quota_type,json=quotaType,proto3" json:"quota_type,omitempty"`
	ApprovalMaxChoices *wrappers.Int32Value   `protobuf:"bytes,10,opt,name=approval_max_choices,json=approvalMaxChoices,proto3" json:"approval_max_choices,omitempty"`
	RankingTopK        *wrappers.Int32Value   `protobuf:"bytes,11,opt,name=ranking_top_k,json=rankingTopK,proto3" json:"ranking_top_k,omitempty"`
	ScoreMin           *wrappers.Int32Value   `protobuf:"bytes,12,opt,name=score_min,json=scoreMin,proto3" json:"score_min,omitempty"`
	ScoreMax           *wrappers.Int32Value   `protobuf:"bytes,13,opt,name=score_max,json=scoreMax,proto3" json:"score_max,omitempty"`
	ScoreStep          *wrappers.Int32Value   `protobuf:"bytes,14,opt,name=score_step,json=scoreStep,proto3" json:"score_step,omitempty"`
	ScoreAllowSkip     *wrappers.BoolValue    `protobuf:"bytes,15,opt,name=score_allow_skip,json=scoreAllowSkip,proto3" json:"score_allow_skip,omitempty"`
	ParamsJson         []byte                 `protobuf:"bytes,16,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	Candidates         []*Candidate           `protobuf:"bytes,17,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunHeader) Reset() {
	*x = RunHeader{}
	mi := &file_compute_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHeader) ProtoMessage() {}

func (x *RunHeader) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHeader.ProtoReflect.Descriptor instead.
func (*RunHeader) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RunHeader) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RunHeader) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunHeader) GetElectionId() string {
	if x != nil {
		return x.ElectionId
	}
	return ""
}

func (x *RunHeader) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *RunHeader) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *RunHeader) GetTallyRule() string {
	if x != nil {
		return x.TallyRule
	}
	return ""
}

func (x *RunHeader) GetBallotFormat() string {
	if x != nil {
		return x.BallotFormat
	}
	return ""
}

func (x *RunHeader) GetCommitteeSize() *wrappers.Int32Value {
	if x != nil {
		return x.CommitteeSize
	}
	return nil
}

func (x *RunHeader) GetQuotaType() *wrappers.StringValue {
	if x != nil {
		return x.QuotaType
	}
	return nil
}

func (x *RunHeader) GetApprovalMaxChoices() *wrappers.Int32Value {
	if x != nil {
		return x.ApprovalMaxChoices
	}
	return nil
}

func (x *RunHeader) GetRankingTopK() *wrappers.Int32Value {
	if x != nil {
		return x.RankingTopK
	}
	return nil
}

func (x *RunHeader) GetScoreMin() *wrappers.Int32Value {
	if x != nil {
		return x.ScoreMin
	}
	return nil
}

func (x *RunHeader) GetScoreMax() *wrappers.Int32Value {
	if x != nil {
		return x.ScoreMax
	}
	return nil
}

func (x *RunHeader) GetScoreStep() *wrappers.Int32Value {
	if x != nil {
		return x.ScoreStep
	}
	return nil
}

func (x *RunHeader) GetScoreAllowSkip() *wrappers.BoolValue {
	if x != nil {
		return x.ScoreAllowSkip
	}
	return nil
}

func (x *RunHeader) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *RunHeader) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ApprovalBallot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approvals     []string               `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalBallot) Reset() {
	*x = ApprovalBallot{}
	mi := &file_compute_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalBallot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalBallot) ProtoMessage() {}

func (x *ApprovalBallot) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalBallot.ProtoReflect.Descriptor instead.
func (*ApprovalBallot) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalBallot) GetApprovals() []string {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type RankingBallot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranking       []string               `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingBallot) Reset() {
	*x = RankingBallot{}
	mi := &file_compute_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingBallot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingBallot) ProtoMessage() {}

func (x *RankingBallot) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingBallot.ProtoReflect.Descriptor instead.
func (*RankingBallot) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{3}
}

func (x *RankingBallot) GetRanking() []string {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_compute_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreEntry) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *ScoreEntry) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ScoreBallot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*ScoreEntry          `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreBallot) Reset() {
	*x = ScoreBallot{}
	mi := &file_compute_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBallot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBallot) ProtoMessage() {}

func (x *ScoreBallot) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBallot.ProtoReflect.Descriptor instead.
func (*ScoreBallot) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreBallot) GetScores() []*ScoreEntry {
	if x != nil {
		return x.Scores
	}
	return nil
}

type Ballot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VoterRef string                 `protobuf:"bytes,1,opt,name=voter_ref,json=voterRef,proto3" json:"voter_ref,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Ballot_Approval
	//	*Ballot_Ranking
	//	*Ballot_Score
	Payload       isBallot_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_compute_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{6}
}

func (x *Ballot) GetVoterRef() string {
	if x != nil {
		return x.VoterRef
	}
	return ""
}

func (x *Ballot) GetPayload() isBallot_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Ballot) GetApproval() *ApprovalBallot {
	if x != nil {
		if x, ok := x.Payload.(*Ballot_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *Ballot) GetRanking() *RankingBallot {
	if x != nil {
		if x, ok := x.Payload.(*Ballot_Ranking); ok {
			return x.Ranking
		}
	}
	return nil
}

func (x *Ballot) GetScore() *ScoreBallot {
	if x != nil {
		if x, ok := x.Payload.(*Ballot_Score); ok {
			return x.Score
		}
	}
	return nil
}

type isBallot_Payload interface {
	isBallot_Payload()
}

type Ballot_Approval struct {
	Approval *ApprovalBallot `protobuf:"bytes,2,opt,name=approval,proto3,oneof"`
}

type Ballot_Ranking struct {
	Ranking *RankingBallot `protobuf:"bytes,3,opt,name=ranking,proto3,oneof"`
}

type Ballot_Score struct {
	Score *ScoreBallot `protobuf:"bytes,4,opt,name=score,proto3,oneof"`
}

func (*Ballot_Approval) isBallot_Payload() {}

func (*Ballot_Ranking) isBallot_Payload() {}

func (*Ballot_Score) isBallot_Payload() {}

type BallotBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballots       []*Ballot              `protobuf:"bytes,1,rep,name=ballots,proto3" json:"ballots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotBatch) Reset() {
	*x = BallotBatch{}
	mi := &file_compute_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotBatch) ProtoMessage() {}

func (x *BallotBatch) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotBatch.ProtoReflect.Descriptor instead.
func (*BallotBatch) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{7}
}

func (x *BallotBatch) GetBallots() []*Ballot {
	if x != nil {
		return x.Ballots
	}
	return nil
}

type RunChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*RunChunk_Header
	//	*RunChunk_Batch
	Part          isRunChunk_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunChunk) Reset() {
	*x = RunChunk{}
	mi := &file_compute_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunChunk) ProtoMessage() {}

func (x *RunChunk) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunChunk.ProtoReflect.Descriptor instead.
func (*RunChunk) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{8}
}

func (x *RunChunk) GetPart() isRunChunk_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *RunChunk) GetHeader() *RunHeader {
	if x != nil {
		if x, ok := x.Part.(*RunChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RunChunk) GetBatch() *BallotBatch {
	if x != nil {
		if x, ok := x.Part.(*RunChunk_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isRunChunk_Part interface {
	isRunChunk_Part()
}

type RunChunk_Header struct {
	Header *RunHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RunChunk_Batch struct {
	Batch *BallotBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*RunChunk_Header) isRunChunk_Part() {}

func (*RunChunk_Batch) isRunChunk_Part() {}

type RunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorText     string                 `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	WinnersJson   []byte                 `protobuf:"bytes,5,opt,name=winners_json,json=winnersJson,proto3" json:"winners_json,omitempty"`
	MetricsJson   []byte                 `protobuf:"bytes,6,opt,name=metrics_json,json=metricsJson,proto3" json:"metrics_json,omitempty"`
	ProtocolJson  []byte                 `protobuf:"bytes,7,opt,name=protocol_json,json=protocolJson,proto3" json:"protocol_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_compute_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_compute_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_compute_v1_proto_rawDescGZIP(), []int{9}
}

func (x *RunResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunResult) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

func (x *RunResult) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RunResult) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *RunResult) GetWinnersJson() []byte {
	if x != nil {
		return x.WinnersJson
	}
	return nil
}

func (x *RunResult) GetMetricsJson() []byte {
	if x != nil {
		return x.MetricsJson
	}
	return nil
}

func (x *RunResult) GetProtocolJson() []byte {
	if x != nil {
		return x.ProtocolJson
	}
	return nil
}

var File_compute_v1_proto protoreflect.FileDescriptor

const file_compute_v1_proto_rawDesc = "" +
	"\n" +
	"\x10compute_v1.proto\x12\x17securevoting.compute.v1\x1a\x1egoogle/protobuf/wrappers.proto\"/\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcb\x06\n" +
	"\tRunHeader\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\velection_id\x18\x03 \x01(\tR\n" +
	"electionId\x12#\n" +
	"\rexperiment_id\x18\x04 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x05 \x01(\tR\tdatasetId\x12\x1d\n" +
	"\n" +
	"tally_rule\x18\x06 \x01(\tR\ttallyRule\x12#\n" +
	"\rballot_format\x18\a \x01(\tR\fballotFormat\x12B\n" +
	"\x0ecommittee_size\x18\b \x01(\v2\x1b.google.protobuf.Int32ValueR\rcommitteeSize\x12;\n" +
	"\n" +
	"quota_type\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\tquotaType\x12M\n" +
	"\x14approval_max_choices\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int32ValueR\x12approvalMaxChoices\x12?\n" +
	"\rranking_top_k\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\vrankingTopK\x128\n" +
	"\tscore_min\x18\f \x01(\v2\x1b.google.protobuf.Int32ValueR\bscoreMin\x128\n" +
	"\tscore_max\x18\r \x01(\v2\x1b.google.protobuf.Int32ValueR\bscoreMax\x12:\n" +
	"\n" +
	"score_step\x18\x0e \x01(\v2\x1b.google.protobuf.Int32ValueR\tscoreStep\x12D\n" +
	"\x10score_allow_skip\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueR\x0escoreAllowSkip\x12\x1f\n" +
	"\vparams_json\x18\x10 \x01(\fR\n" +
	"paramsJson\x12B\n" +
	"\n" +
	"candidates\x18\x11 \x03(\v2\".securevoting.compute.v1.CandidateR\n" +
	"candidates\".\n" +
	"\x0eApprovalBallot\x12\x1c\n" +
	"\tapprovals\x18\x01 \x03(\tR\tapprovals\")\n" +
	"\rRankingBallot\x12\x18\n" +
	"\aranking\x18\x01 \x03(\tR\aranking\"E\n" +
	"\n" +
	"ScoreEntry\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"J\n" +
	"\vScoreBallot\x12;\n" +
	"\x06scores\x18\x01 \x03(\v2#.securevoting.compute.v1.ScoreEntryR\x06scores\"\xf9\x01\n" +
	"\x06Ballot\x12\x1b\n" +
	"\tvoter_ref\x18\x01 \x01(\tR\bvoterRef\x12E\n" +
	"\bapproval\x18\x02 \x01(\v2'.securevoting.compute.v1.ApprovalBallotH\x00R\bapproval\x12B\n" +
	"\aranking\x18\x03 \x01(\v2&.securevoting.compute.v1.RankingBallotH\x00R\aranking\x12<\n" +
	"\x05score\x18\x04 \x01(\v2$.securevoting.compute.v1.ScoreBallotH\x00R\x05scoreB\t\n" +
	"\apayload\"H\n" +
	"\vBallotBatch\x129\n" +
	"\aballots\x18\x01 \x03(\v2\x1f.securevoting.compute.v1.BallotR\aballots\"\x8e\x01\n" +
	"\bRunChunk\x12<\n" +
	"\x06header\x18\x01 \x01(\v2\".securevoting.compute.v1.RunHeaderH\x00R\x06header\x12<\n" +
	"\x05batch\x18\x02 \x01(\v2$.securevoting.compute.v1.BallotBatchH\x00R\x05batchB\x06\n" +
	"\x04part\"\xe6\x01\n" +
	"\tRunResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_text\x18\x02 \x01(\tR\terrorText\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\fR\n" +
	"paramsJson\x12!\n" +
	"\fwinners_json\x18\x05 \x01(\fR\vwinnersJson\x12!\n" +
	"\fmetrics_json\x18\x06 \x01(\fR\vmetricsJson\x12#\n" +
	"\rprotocol_json\x18\a \x01(\fR\fprotocolJson2Y\n" +
	"\aCompute\x12N\n" +
	"\x03Run\x12!.securevoting.compute.v1.RunChunk\x1a\".securevoting.compute.v1.RunResult(\x01B3Z1secure-voting/apps/backend/internal/compute/pb;pbb\x06proto3"

var (
	file_compute_v1_proto_rawDescOnce sync.Once
	file_compute_v1_proto_rawDescData []byte
)

func file_compute_v1_proto_rawDescGZIP() []byte {
	file_compute_v1_proto_rawDescOnce.Do(func() {
		file_compute_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_v1_proto_rawDesc), len(file_compute_v1_proto_rawDesc)))
	})
	return file_compute_v1_proto_rawDescData
}

var file_compute_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_compute_v1_proto_goTypes = []any{
	(*Candidate)(nil),            // 0: securevoting.compute.v1.Candidate
	(*RunHeader)(nil),            // 1: securevoting.compute.v1.RunHeader
	(*ApprovalBallot)(nil),       // 2: securevoting.compute.v1.ApprovalBallot
	(*RankingBallot)(nil),        // 3: securevoting.compute.v1.RankingBallot
	(*ScoreEntry)(nil),           // 4: securevoting.compute.v1.ScoreEntry
	(*ScoreBallot)(nil),          // 5: securevoting.compute.v1.ScoreBallot
	(*Ballot)(nil),               // 6: securevoting.compute.v1.Ballot
	(*BallotBatch)(nil),          // 7: securevoting.compute.v1.BallotBatch
	(*RunChunk)(nil),             // 8: securevoting.compute.v1.RunChunk
	(*RunResult)(nil),            // 9: securevoting.compute.v1.RunResult
	(*wrappers.Int32Value)(nil),  // 10: google.protobuf.Int32Value
	(*wrappers.StringValue)(nil), // 11: google.protobuf.StringValue
	(*wrappers.BoolValue)(nil),   // 12: google.protobuf.BoolValue
}
var file_compute_v1_proto_depIdxs = []int32{
	10, // 0: securevoting.compute.v1.RunHeader.committee_size:type_name -> google.protobuf.Int32Value
	11, // 1: securevoting.compute.v1.RunHeader.quota_type:type_name -> google.protobuf.StringValue
	10, // 2: securevoting.compute.v1.RunHeader.approval_max_choices:type_name -> google.protobuf.Int32Value
	10, // 3: securevoting.compute.v1.RunHeader.ranking_top_k:type_name -> google.protobuf.Int32Value
	10, // 4: securevoting.compute.v1.RunHeader.score_min:type_name -> google.protobuf.Int32Value
	10, // 5: securevoting.compute.v1.RunHeader.score_max:type_name -> google.protobuf.Int32Value
	10, // 6: securevoting.compute.v1.RunHeader.score_step:type_name -> google.protobuf.Int32Value
	12, // 7: securevoting.compute.v1.RunHeader.score_allow_skip:type_name -> google.protobuf.BoolValue
	0,  // 8: securevoting.compute.v1.RunHeader.candidates:type_name -> securevoting.compute.v1.Candidate
	4,  // 9: securevoting.compute.v1.ScoreBallot.scores:type_name -> securevoting.compute.v1.ScoreEntry
	2,  // 10: securevoting.compute.v1.Ballot.approval:type_name -> securevoting.compute.v1.ApprovalBallot
	3,  // 11: securevoting.compute.v1.Ballot.ranking:type_name -> securevoting.compute.v1.RankingBallot
	5,  // 12: securevoting.compute.v1.Ballot.score:type_name -> securevoting.compute.v1.ScoreBallot
	6,  // 13: securevoting.compute.v1.BallotBatch.ballots:type_name -> securevoting.compute.v1.Ballot
	1,  // 14: securevoting.compute.v1.RunChunk.header:type_name -> securevoting.compute.v1.RunHeader
	7,  // 15: securevoting.compute.v1.RunChunk.batch:type_name -> securevoting.compute.v1.BallotBatch
	8,  // 16: securevoting.compute.v1.Compute.Run:input_type -> securevoting.compute.v1.RunChunk
	9,  // 17: securevoting.compute.v1.Compute.Run:output_type -> securevoting.compute.v1.RunResult
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_compute_v1_proto_init() }
func file_compute_v1_proto_init() {
	if File_compute_v1_proto != nil {
		return
	}
	file_compute_v1_proto_msgTypes[6].OneofWrappers = []any{
		(*Ballot_Approval)(nil),
		(*Ballot_Ranking)(nil),
		(*Ballot_Score)(nil),
	}
	file_compute_v1_proto_msgTypes[8].OneofWrappers = []any{
		(*RunChunk_Header)(nil),
		(*RunChunk_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_v1_proto_rawDesc), len(file_compute_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_v1_proto_goTypes,
		DependencyIndexes: file_compute_v1_proto_depIdxs,
		MessageInfos:      file_compute_v1_proto_msgTypes,
	}.Build()
	File_compute_v1_proto = out.File
	file_compute_v1_proto_goTypes = nil
	file_compute_v1_proto_depIdxs = nil
}
