name: "Compute-core pipeline"
on:
  push:
    branches:
      - 'dev'
      - 'master'
      - 'ci/**'

jobs:
  ci:
    name: rust-ci
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
      - name: "Get protoc"
        run: "sudo apt-get install protobuf-compiler"

      - name: "Setup Toolchain"
        uses: "moonrepo/setup-toolchain@v0"

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: compute-core

      - name: "Execute pipeline"
        run: "moon ci -c 1 --color"

      - name: "Collect results"
        uses: "appthrust/moon-ci-retrospect@v2"
        if: success() || failure()

